#!/bin/bash
#usage vzumount $CTID
set -e
if [ -z $1 ]; then
	echo "no CTID"
	exit 1
fi

CTID=$1
POOL=rbd

if [ -h /dev/rbd/$POOL/shell-${CTID} ]; then
	umount /dev/rbd/$POOL/shell-${CTID}
	rbd unmap /dev/rbd/$POOL/shell-${CTID}
else
	echo failed
fi
exit 0
